### ISSUE TITLE
Alternative Approach

### ISSUE THREAD

**Issue by MiguelMadero** [ef4/ember-giftwrap#6]
Hi @ef4, we have been using a `packaging` mechanism internally to precompile and distribute our assets from one of our ember add-ons, so a non ember-cli app can consume it. This approach was heavily inspired by the way that liquid-fire is doing it. I extracted this into it's own add-on (see [ember-package](https://github.com/practicefusion/ember-package)). 

The goals of this two projects are really similar, but the approach is a bit different. 

In ember-package, I'm targeting two different use cases (more details on the [README](https://github.com/practicefusion/ember-package)), authors that want to distribute static assets and apps that want to compile those assets on the fly. The main difference is that the addons will be compiled in-place using a standalone command instead of having to create an ember-cli app and it will generate individual js/css files instead of a one, which addresses one of the "Known Caveats". Some of the disadvantages of ember-package is that it doesn't use an EmberApp, bur relies on broccoli directly, it also, doesn't provide a way to "install" the app or pass configuration to addons. 

Ember-package started from scratching our own itch, I was excited when I looked at ember-giftwrap, but since we're using this for add-ons that change really often, it doesn't seem that easy to keep updating the addons if it depends on a separate app or to `npm link` the addon and rebuild as we change the source. 

One idea, I had for GiftWrap, to create the ember-cli app inside the app, sync the package.json with the parent app and build/serve in-place. 

I will appreciate your feedback. 

**DISCLAIMER:** for anyone reading this, ember-package is really early and my main intention of posting here is to bounce some ideas with @ef4  or anyone else interested, but I'm not suggesting to use ember-package as a replacement.

**Comment by ef4** [comment]
It's actually already possible to use giftwrap in the way you describe -- adding it directly to the addon's project and building the addon for distribution. That can definitely make sense for internal use. Liquid Fire actually has this capability, just checkout the repo and run "ember giftwrap" and it will spit out a build.

_(With one caveat: if your addon has other addon dependencies that should only be used during testing, and not distributed, today they will get included in the package. We should add an option to filter them out.)_

But for the wider ecosystem, there are both social and technical reasons I'd rather have addon consumers running the tool, rather than addon authors.

The technical reason is that any addon containing templates needs to get built by the precise version of Ember (right down to the sha) that it's going to run with. So to distribute that addon, you would need to do a whole matrix of builds, and publish new ones whenever Ember releases. Which is annoying, and you can imagine addons lagging behind and making it hard for people to upgrade.

The social reason is that I don't want to create two fragmented classes of addons -- ones that distribute packages and ones that don't. My ideal goal is for addon authors to have zero extra work to do, so that every addon is automatically usable.
